config/routes.rb
Rails.application.routes.draw do
  resources :protests do
    post 'rsvp'
    get 'admin'
    post 'admin/notify', to: 'protests#notify'
  end

  get 'upload_image/:key', to: 'protests#image_upload', as: 'protests_image_upload'
  post 'upload_image/:key', to: 'protests#upload', as: 'protests_upload'

  root to: 'protests#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/organizer.rb
class Organizer < ApplicationRecord
  has_many :protests
end

app/models/protest.rb
class Protest < ApplicationRecord
  has_many :organizers
  has_many :users, through: :organizers

  has_many :rsvp_people

  has_many_attached :images

  geocoded_by :location
  after_validation :geocode

  before_save :add_image_key

  def protestors
    rsvp_people
  end 

  def lat
    latitude
  end

  def lng
    longitude
  end

  def generate_pdf
    pdf = Prawn::Document.new
    pdf.text "hi!"
    pdf
  end

  def upload_image_url
    "https://protestor-ljctmb.herokuapp.com/upload_image/#{self.image_key}"
  end

  def upload_image_qr
    RQRCode::QRCode.new(upload_image_url).as_png
  end

  include Rails.application.routes.url_helpers
  def public_url
    "https://protestor-ljctmb.herokuapp.com#{protest_path(self)}"
  end

  def twitter_url
    social_network(:twitter, '/share', text: name, url: public_url)
  end

  def facebook_url
    social_network(:facebook, '/sharer/sharer.php', u: public_url)
  end

  private

  def add_image_key
    unless self.image_key
      self.image_key = ('a'..'z').to_a.shuffle[0, 8].join
    end
  end

  def social_network(name, sharer, options = {})
    "https://#{name}.com#{sharer}?#{options.to_query}"
  end
end

app/models/rsvp_person.rb
class RsvpPerson < ApplicationRecord
  belongs_to :protest

  validates :name, :presence => true
  validates :email, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/protests_controller.rb
class ProtestsController < ApplicationController
  before_action :set_protest, only: [:show, :edit, :update, :destroy]
  before_action :set_protest_id, only: [:rsvp, :admin, :notify]

  # GET /protests
  # GET /protests.json
  def index
    @protests = Protest.all
  end

  # GET /protests/1
  # GET /protests/1.json
  def show
    @rsvp_person = @protest.rsvp_people.new

    respond_to do |format|
      format.html
      format.pdf do
       render file: 'protests/show.pdf',
           content_type: 'application/pdf',
           filename: @protest.name,
           disposition: 'inline'
      end
    end
  end

  # GET /protests/new
  def new
    @protest = Protest.new
  end

  # GET /protests/1/edit
  def edit
  end

  # POST /protests
  # POST /protests.json
  def create
    @protest = Protest.new(protest_params)

    respond_to do |format|
      if @protest.save
        format.html { redirect_to @protest, notice: 'Protest was successfully created.' }
        format.json { render :show, status: :created, location: @protest }
      else
        format.html { render :new }
        format.json { render json: @protest.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /protests/1
  # PATCH/PUT /protests/1.json
  def update
    respond_to do |format|
      if @protest.update(protest_params)
        format.html { redirect_to @protest, notice: 'Protest was successfully updated.' }
        format.json { render :show, status: :ok, location: @protest }
      else
        format.html { render :edit }
        format.json { render json: @protest.errors, status: :unprocessable_entity }
      end
    end
  end

  def rsvp
    if @protest.rsvp_people.create(rsvp_params)
      redirect_to @protest, notice: "You've successfully RSVP'd for #{@protest.name}!"
    else
      render :show
    end
  end

  def notify
    SendTwilioMessagesJob.perform_now(@protest.rsvp_people.pluck(:phone_number), params[:message])
    flash[:success] = "Message sent to #{@protest.rsvp_people.count} protesters!"
    redirect_to protest_admin_path(@protest)
  end

  def admin
  end

  def image_upload
    @protest = Protest.find_by_image_key(params[:key])
    redirect_to protests_path, notice: "Invalid key!" unless @protest
  end

  def upload
    @protest = Protest.find_by_image_key(params[:key])
    redirect_to protests_path, notice: "Invalid key!" unless @protest
    if @protest.update(image_upload_params)
      flash[:success] = "Your image(s) have been uploaded!"
      redirect_to protests_path
    else
      redirect_to protests_path
    end
  end


  # DELETE /protests/1
  # DELETE /protests/1.json
  def destroy
    @protest.destroy
    respond_to do |format|
      format.html { redirect_to protests_url, notice: 'Protest was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_protest
      @protest = Protest.find(params[:id])
    end

    def set_protest_id
      @protest = Protest.find(params[:protest_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def protest_params
      params.require(:protest).permit(:name, :location, :description, :start, :end, :what_to_bring, :organizer_id)
    end

    def rsvp_params
      params.require(:rsvp_person).permit(:name, :email, :phone_number)
    end

    def image_upload_params
      params.require(:protest).permit(images: [])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include ActionView::Helpers

  def format_time(time)
    local_time(time, '%B %e, %Y %l:%M%P %Z')
  end

  def event_length(event)
    "#{local_time(event.start, '%B %e, %Y. %l:%M%P')} -#{local_time(event.end, '%l:%M%P')}"
  end

  def event_time_plain(event)
    "#{event.start.strftime '%B %e, %l:%M%P'} -#{event.end.strftime '%l:%M%P'}"
  end

  def event_times(event)
    "#{local_time(event.start, '%l:%M%P')} -#{local_time(event.end, '%l:%M%P')}"
  end

  def blankslate(text, options = {})
    other_options = options.except(:class)
    content_tag(:p, text, class: "mt0 mb0 pt2 pb2 slate bold h3 #{options[:class]}", **other_options)
  end

  def filterbar_blankslate(text, options = {})
    blankslate(text, 'data-behavior': 'filterbar_blankslate', class: 'mt2 mb2', **options)
  end

  def badge_for(count, options = {})
    content_tag :span, count, class: "badge #{options[:class]} #{'bg-muted' if count == 0}"
  end

  def status_badge(type = :pending)
    content_tag :span, '', class: "status bg-#{type}"
  end

  def status_if(type, condition)
    status_badge(type) if condition
  end

  def pop_icon_to(icon, url, options = {})
    link_to url, options.merge({ class: "pop #{options[:class]}" }) do
      inline_icon icon, size: options[:size] || 36
    end
  end

  def relative_timestamp(time, options = {})
    content_tag :span, "#{options[:prefix]}#{time_ago_in_words time} ago", options.merge({ title: time })
  end

  def auto_link_new_tab(text)
    auto_link(text, html: { target: '_blank' })
  end

  def debug_obj(object)
    content_tag :pre, pp(item.attributes.to_yaml)
  end

  def inline_icon(filename, options = {})
    file = File.read(Rails.root.join('app', 'assets', 'images', 'icons', "#{filename}.svg"))
    doc = Nokogiri::HTML::DocumentFragment.parse file
    svg = doc.at_css 'svg'
    options[:style] ||= ''
    if options[:size]
      options[:width] = options[:size]
      options[:height] = options[:size]
      options.delete :size
    end
    options.each { |key, value| svg[key.to_s] = value }
    doc.to_html.html_safe
  end

  def filterbar_item(label, name, selected = false)
    content_tag :a, label, class: 'filterbar__item',
    tabindex: 0, role: 'tab', 'aria-selected': selected,
    data: { name: name.to_s, behavior: 'filterbar_item' }
  end

  def map_url(lat = 41.838796, lng = -83.200725, options = {})
    "https://dev.virtualearth.net/REST/v1/Imagery/Map/Aerial/#{lat},#{lng}/15/?mapSize=2000,600&format=png&key=AssBchuxLMpaS6MmACdfDyLpD4X7_T2SZ34cC_KBcWlPU6iZCsWgv0tTbw5Coehm"
  end

  def page_md
    content_for(:container_class) { 'container--md' }
  end

  def page_sm
    content_for(:container_class) { 'container--sm' }
  end
  alias_method :page_narrow, :page_sm

  def page_xs
    content_for(:container_class) { 'container--xs' }
  end
  alias_method :page_extranarrow, :page_xs

  def title(text)
    content_for :title, text
  end
end

app/helpers/protests_helper.rb
module ProtestsHelper
end

app/views/layouts/_nav.html.erb
<header class="flex items-center justify-between mt3 container <%= content_for :container_class %>">
  <%= link_to root_path do %>
    <%= image_tag '/flag.svg', alt: 'Logo' %>
  <% end %>
  <nav class="flex items-center">
    <%= link_to 'Upcoming', protests_path, class: 'text-decoration-none slate' %>
    <%= link_to 'Organize', new_protest_path, class: 'btn bg-primary ml2 md-ml3' %>
  </nav>
</header>

<% flash.each do |key, value| %>
  <article role="alertdialog" class="flash flex items-center mt3 mb2 mx-auto <%= key %>" data-behavior="flash">
    <span class="flex-auto"><%= value %></span>
    <%= inline_icon 'view-close', size: 32, class: 'pointer' %>
  </article>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>
      <%= "#{yield(:title)} – " if content_for?(:title) %>
      Protestor
    </title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/galleria/1.5.7/galleria.min.js"></script>
    <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
    <link rel="manifest" href="/site.webmanifest">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#69ff00">
    <meta name="msapplication-TileColor" content="#69ff00">
    <meta name="theme-color" content="#69ff00">
  </head>
  <body class="bg-snow <%= content_for :page_class %>">
    <%= render 'layouts/nav' %>
    <main class="container <%= content_for :container_class %>">
      <%= yield %>
    </main>
  </body>
</html>

app/views/protests/_form.html.erb
<%= form_with(model: protest, local: true) do |form| %>
  <% if protest.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(protest.errors.count, "error") %> prohibited this protest from being saved:</h2>

      <ul>
      <% protest.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, placeholder: 'Youth Demonstration for Climate Change @ the White House' %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_area :location, placeholder: '1600 Pennsylvania Ave NW, Washington, DC 20500' %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, placeholder: 'The current administration denies climate change…' %>
  </div>

  <div class="field">
    <%= form.label :start, 'Start time' %>
    <%= form.datetime_select :start %>
  </div>

  <div class="field">
    <%= form.label :end, 'End time' %>
    <%= form.datetime_select :end %>
  </div>

  <div class="field">
    <%= form.label :what_to_bring %>
    <%= form.text_area :what_to_bring, placeholder: 'Protest signs', class: 'max-width-1' %>
    <p class="muted h5 mt0">Put one item on each line.</p>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/protests/_rsvp_form.html.erb
<%= form_with(model: @rsvp_person, local: true, url: protest_rsvp_path(protest)) do |form| %>
  <% if @rsvp_person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rsvp_person.errors.count, "error") %> prohibited this protest from being saved:</h2>

      <ul>
      <% @rsvp_person.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.email_field :email %>
  </div>

  <div class="field">
    <%= form.label :phone_number %>
    <%= form.telephone_field :phone_number %>
  </div>

  <div class="actions">
    <%= form.submit 'Submit' %>
  </div>
<% end %>

app/views/protests/admin.html.erb
<%= link_to 'Normal view', @protest, class: 'block mt2 breadcrumb' %>
<h1 class="flex items-center">
  <%= inline_icon 'admin-badge', size: 36, class: 'warning mr1' %>
  <span class="h1 flex-auto"><%= @protest.name %></span>
  <%= link_to 'Edit', edit_protest_path(@protest), class: 'btn' %>
</h1>

<div class="details">
<p>
  <strong>Location</strong>
  <%= @protest.location %>
</p>

<p>
  <strong>Description</strong>
  <%= @protest.description %>
</p>

<div>
  <strong>What to bring</strong>
  <ul class="mt0 mb0"><%= @protest.what_to_bring.lines.map { |li| content_tag :li, li }.join.html_safe %></ul>
</div>
</div>

<h2 class="flex items-center">
  RSVPs
  <%= badge_for @protest.rsvp_people.size %>
</h2>
<% if @protest.rsvp_people.any? %>
<table>
  <tr>
    <th>Name</th>
    <th>Emails</th>
    <th>Phone Numbers</th>
  </tr>
  <% @protest.rsvp_people.each do |person| %>
    <tr>
      <td><%= person.name %></td>
      <td><%= person.email %></td>
      <td><%= person.phone_number %></td>
    </tr>
  <% end %>
</table>
<% else %>
  <%= blankslate 'No RSVPs yet' %>
<% end %>

<div class="grid grid--spacious mt3">
  <div class="card bg-notify">
    <h2 class="flex items-center mt0">
      <%= inline_icon 'message', size: 36, class: 'mr1' %>
      Notify all protestors
    </h2>
    <p class="mt0">Send an SMS blast to all your attendees.</p>

    <%= form_tag(protest_admin_notify_path(@protest), method: "post") do %>
      <%= label_tag :message %>
      <%= text_area_tag :message %>
      <%= submit_tag "Send!" %>
    <% end %>
  </div>

  <div>

  <div class="card bg-media mb2 md-mb3">
    <h2 class="flex items-center mt0">
      <%= inline_icon 'photo', size: 36, class: 'mr1' %>
      Image upload URL
    </h2>
    <p class="mt0">Distibute to trusted organizers to upload event media.</p>
    <strong><a href="https://protestor-ljctmb.herokuapp.com/upload_image/<%= @protest.image_key %>">protestor-ljctmb.herokuapp.com/upload_image/<%= @protest.image_key %></a></strong>
  </div>

  <div class="card bg-poster">
    <h2 class="flex items-center mt0">
      <%= inline_icon 'send', size: 36, class: 'mr1' %>
      Share the event
    </h2>
    <div>
      <%= link_to 'Print poster', protest_path(@protest, format: :pdf), target: '_blank', class: 'btn' %>
      <%= link_to 'Twitter', @protest.twitter_url, target: '_blank', class: 'btn' %>
      <%= link_to 'Facebook', @protest.facebook_url, target: '_blank', class: 'btn' %>
    </div>
  </div>
  </div>
</div>

app/views/protests/edit.html.erb
<% page_sm %>

<%= link_to @protest.name, @protest, class: 'breadcrumb mt2 block' %>
<h1>Editing Protest</h1>

<%= render 'form', protest: @protest %>

app/views/protests/image_upload.html.erb
<h2>Upload images to <%= @protest.name %></h2>

<%= form_with(model: @protest, local: true, url: protests_upload_path, method: :post) do |form| %>
  <% if @protest.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@protest.errors.count, "error") %> prohibited these images from being saved:</h2>

      <ul>
      <% @protest.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= form.file_field :images, multiple: true %>
  </div>

  <div class="actions">
    <%= form.submit "Upload Images" %>
  </div>
<% end %>

app/views/protests/index.html.erb
<% page_md %>

<h1>Upcoming events</h1>
<p class="h3">Near <span class="primary medium underline-dotted">Sunnyvale, CA</span></p>

<% @protests.each do |protest| %>
  <%= link_to protest, class: 'mb3 card block text-decoration-none black' do %>
    <h2 class="mt0"><%= protest.name %></h2>
    <p><%= protest.description %></p>
    <div class="flex items-center">
      <%= inline_icon 'map-pin', size: 24, class: 'muted mr1' %>
      <%= protest.location %>
    </div>
  <% end %>
<% end %>

app/views/protests/new.html.erb
<% page_sm %>

<h1>Post your protest</h1>

<%= render 'form', protest: @protest %>

app/views/protests/show.html.erb
<% page_md %>

</main>
<header class="w-100 map-header" style="background-image: url(<%= map_url(@protest.lat, @protest.lng) %>);">
  <div class="container container--md">
    <%= link_to 'All Events', protests_path, class: 'breadcrumb block h3 mt3' %>
    <h1 class="heading"><%= @protest.name %></h1>
    <%= pop_icon_to 'admin-badge', protest_admin_path(@protest), class: 'warning right ml2 tooltipped tooltipped--s', 'aria-label': 'Admin tools for this event' %>
  </div>
</header>

<main class="container container--md">

<p class="h2">
  <%= @protest.description %>
</p>

<div class="flex items-center mt2 mb2">
  <div class="calendar mr2">
    <span class="calendar__month"><%= @protest.start.strftime('%B') %></span>
    <span class="calendar__day"><%= @protest.start.day %></span>
  </div>
  <div>
    <h2 class="h5 caps mt0 mb0">From–to</h2>
    <span class="h3"><%= event_times(@protest).html_safe %></span>
  </div>
</div>

<iframe src="https://www.google.com/maps/embed/v1/view?key=AIzaSyAzUu3beD2W1qG04YTGrxq_-vvcDq78jew&center=<%= @protest.lat %>,<%= @protest.lng %>&zoom=18%20" frameborder="0" class="md-right"></iframe>

<p>
  <h2 class="h5 caps">Location</h2>
  <%= @protest.location %>
</p>

<div>
  <h2 class="h5 caps">What to bring</h2>
  <ul class="list-style-none m0 p0">
    <% @protest.what_to_bring.lines.each do |line| %>
    <li class="flex items-center mb1">
      <%= inline_icon 'checkmark', size: 32, class: 'muted mr1' %>
      <span><%= line %></span>
    </li>
    <% end %>
  </ul>
</div>

<article class="card max-width-2 mx-auto mt3 md-mt4">
  <h2 class="mt0 mb2 pb1 border-bottom">RSVP for the protest (<%= rand(12..100) %> signed up) </h2>
  <p class="slate">Organizers will receive your contact info & can send you updates.</p>
  <%= render 'rsvp_form', protest: @protest %>
</article>

<% if @protest.images.any? %>
  <div class="galleria mt3">
    <% @protest.images.each do |img| %>
      <img src="<%= polymorphic_url(img) %>">
    <% end %>
  </div>
<% end %>